name: Deploy to STAGING

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: drhscit.org
          port: 2323
          username: gritstaging
          key: ${{ secrets.SSH_KEY_GRIT_STAGING }}
          script: |
            cd /home/gritstaging/www
            git pull origin main
