name: Deploy PR Preview
on: pull_request
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Add build steps here
      - name: Deploy PR Preview
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./ # Or your build directory
